--creation des role data_engineer et analyst
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ANALYST;

--Attribuer le rôle DATA_ENGINEER à l’utilisateur
CREATE ROLE DATA_ENGINEER TO USER Lamine;

--creation d'une base de données
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;

--creation des schemas (row, staging, mart)
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.MART;

--Donner au rôle DATA_ENGINEER les droits nécessaires pour créer des objets.;  
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_DB.STAGING TO ROLE data_engineer;
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_DB.MART TO ROLE data_engineer;

GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT CREATE VIEW  ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT MODIFY ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN DATABASE ECOMMERCE_DB TO ROLE DATA_ENGINEER;

SHOW GRANTS TO ROLE DATA_ENGINEER;

--cration d'un werehouse ECOMMERCE_WH avec auto suspent
CREATE WAREHOUSE ECOMMERCE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE DATA_ENGINEER;